dependencies {
    api project(':ical4j-connector-api'), libs.google.api.calendar, libs.google.api.client,
            libs.google.oauth.client.jetty

    testImplementation 'net.bytebuddy:byte-buddy:1.14.19'
    testImplementation 'org.objenesis:objenesis:3.4'
    testImplementation 'org.mockito:mockito-core:5.11.0'
}
