cache:
  directories:
    - $HOME/.gradle
    - $HOME/.sonar
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script:
  - ./gradlew check jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy: "./gradlew assembleDist"
sudo: false
deploy:
  provider: releases
  api_key:
    secure: F/phrNZC+kF8IyHEDyJtQA9P72FBLLUyuWDVn9QvBedhveGRbBkXDx/mpLD5iuir8+fK1Inm+09BMfpX+UoEcS8a6mgbEGqqUX61ZIUpGmXASw0EJbX/Bne7oMrvm4IHYIaRord2+YyGeUOdzCggwoh/wnFlLcL5Q97xyN5N4Ig=
  file:
    - build/distributions/ical4j-$RELEASE_VERSION.zip
    - build/distributions/ical4j-$RELEASE_VERSION.tar.gz
  skip_cleanup: true
  on:
    tags: true
after_script:
  - sudo keytool -import -alias sonar -keystore $JAVA_HOME/jre/lib/security/cacerts -file sonar_cert.pem -storepass changeit -noprompt
  # Check if commit is not a pull request, if git repo is official, and if branch is master. If checks pass, run Sonar reports
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == ical4j/ical4j-connector ]] && [[ $TRAVIS_BRANCH == master ]] && ./gradlew sonarqube"

