plugins {
    id 'org.gradlex.extra-java-module-info' version '1.9'
}

extraJavaModuleInfo {
    deriveAutomaticModuleNamesFromFileNames.set(true)
}

dependencies {
    api project(':ical4j-connector-api'), libs.jetbrains.annotations

    api(libs.httpclient) {
        exclude(group: 'commons-logging', module: 'commons-logging')
    }

    api(libs.jackrabbit.webdav) {
        exclude(group: 'org.apache.httpcomponents', module: 'httpclient')
    }
    implementation 'javax.servlet:servlet-api:2.5', 'org.hamcrest:hamcrest:2.2'
}
