name: Publish snapshots

on:
  push:
    branches:
      - 'develop'
      - 'feature/refactor'

permissions: read-all

jobs:
  test:
    uses: ical4j/ical4j/.github/workflows/test.yml@develop

  publish:
    name: Publish Artifact
    needs: gradle
    if: ${{ needs.gradle.result == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build -x test publish
        env:
          GPR_USERNAME: benfortuna
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
